### PR TITLE
Adam/how to/use preloads revisions

### PR DESCRIPTION
**Pull request by adam-saland**
@johnman just changed a few things:

1. keep consistent with basic naming from workspace etc. 
2. clean up readme a bit. 

I think it is good to go as far as code is concerned.

### CODE REVIEW

**Review by johnman — APPROVED** [review]

**Review by adam-saland — COMMENTED** [review]
looks good ... no code changes just renames :) !

**Review by adam-saland — COMMENTED** [review]
good to go!

**Review by adam-saland — COMMENTED** [review]
good to go!

**Review by adam-saland — COMMENTED** [review]
good to go!

**Review by adam-saland — COMMENTED** [review]
good to go!

**Pull request merged**
